"""
Mesh Auto Scaler — Monitor de Auto-escalado para DOF Mesh.

Observa la carga de los nodos activos en la red y emite recomendaciones
de escalado (scale_up / scale_down) de forma determinista.

Arquitectura:
    MeshAutoScaler (singleton)
        ├── check_load()          — lee nodes.json, detecta overload/idle
        ├── scale_up(node_id)     — genera alerta en autoscaler.jsonl
        ├── scale_down(node_id)   — marca nodo como candidato a retirar
        └── get_recommendations() — devuelve recomendaciones activas

Decisiones deterministas — sin dependencia de LLM.
Logs en logs/mesh/autoscaler.jsonl.
"""

import json
import logging
import threading
import time
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Optional

logger = logging.getLogger("core.mesh_auto_scaler")

# ═══════════════════════════════════════════════════════
# DATA CLASSES
# ═══════════════════════════════════════════════════════


@dataclass
class ScaleEvent:
    """A scaling recommendation generated by the auto-scaler."""
    node_id: str
    event_type: str      # scale_up | scale_down | ok
    reason: str
    active_tasks: int = 0
    timestamp: float = field(default_factory=time.time)


# ═══════════════════════════════════════════════════════
# AUTO SCALER
# ═══════════════════════════════════════════════════════


class MeshAutoScaler:
    """
    Singleton auto-scaling monitor for DOF Mesh.

    Reads logs/mesh/nodes.json on every check_load() call, compares
    active_tasks against configurable thresholds and emits ScaleEvents.
    Recommendations are persisted to logs/mesh/autoscaler.jsonl.
    """

    _instance: Optional["MeshAutoScaler"] = None
    _lock: threading.Lock = threading.Lock()

    def __new__(
        cls,
        overload_threshold: int = 5,
        idle_threshold: int = 0,
        check_interval: int = 30,
        log_dir: Optional[Path] = None,
        mesh_dir: Optional[Path] = None,  # alias for log_dir
    ) -> "MeshAutoScaler":
        if overload_threshold is None or not isinstance(overload_threshold, int):
            raise TypeError(
                f"overload_threshold must be int, got {type(overload_threshold).__name__}"
            )
        with cls._lock:
            if cls._instance is None:
                inst = super().__new__(cls)
                inst._initialized = False
                cls._instance = inst
        return cls._instance

    def __init__(
        self,
        overload_threshold: int = 5,
        idle_threshold: int = 0,
        check_interval: int = 30,
        log_dir: Optional[Path] = None,
        mesh_dir: Optional[Path] = None,  # alias for log_dir
    ) -> None:
        if self._initialized:  # type: ignore[has-type]
            return
        self.overload_threshold = overload_threshold
        self.idle_threshold = idle_threshold
        self.check_interval = check_interval
        self._log_dir: Path = Path(log_dir or mesh_dir or "logs/mesh")
        self._log_dir.mkdir(parents=True, exist_ok=True)
        self._autoscaler_log: Path = self._log_dir / "autoscaler.jsonl"
        self._nodes_file: Path = self._log_dir / "nodes.json"
        # In-memory list of active recommendations (keyed by node_id)
        self._recommendations: dict[str, dict] = {}
        self._initialized = True
        logger.info(
            "MeshAutoScaler initialized — overload=%d idle=%d interval=%ds",
            overload_threshold,
            idle_threshold,
            check_interval,
        )

    # ── internal helpers ──────────────────────────────────────────────────

    def _load_nodes(self) -> dict:
        """Load nodes.json; returns empty dict on missing/corrupt file."""
        if not self._nodes_file.exists():
            return {}
        try:
            with self._nodes_file.open("r", encoding="utf-8") as fh:
                return json.load(fh)
        except (json.JSONDecodeError, OSError) as exc:
            logger.warning("Could not read nodes.json: %s", exc)
            return {}

    def _append_log(self, event: ScaleEvent) -> None:
        """Append a ScaleEvent to autoscaler.jsonl."""
        record = asdict(event)
        try:
            with self._autoscaler_log.open("a", encoding="utf-8") as fh:
                fh.write(json.dumps(record) + "\n")
        except OSError as exc:
            logger.error("Failed to write autoscaler log: %s", exc)

    def _upsert_recommendation(self, event: ScaleEvent) -> None:
        """Keep one recommendation per node (latest wins)."""
        self._recommendations[event.node_id] = asdict(event)

    def _remove_recommendation(self, node_id: str) -> None:
        """Remove recommendation once node is within bounds."""
        self._recommendations.pop(node_id, None)

    # ── public API ────────────────────────────────────────────────────────

    def check_load(self) -> list[ScaleEvent]:
        """
        Read logs/mesh/nodes.json and evaluate every node's active_tasks.

        Returns a list of ScaleEvent items for nodes that breach a threshold.
        Also updates internal recommendations and appends to autoscaler.jsonl.
        """
        nodes = self._load_nodes()
        events: list[ScaleEvent] = []

        for node_id, info in nodes.items():
            active_tasks: int = int(info.get("active_tasks", 0))
            status: str = str(info.get("status", "unknown"))

            if active_tasks > self.overload_threshold:
                evt = ScaleEvent(
                    node_id=node_id,
                    event_type="scale_up",
                    reason=(
                        f"active_tasks={active_tasks} exceeds "
                        f"overload_threshold={self.overload_threshold}"
                    ),
                    active_tasks=active_tasks,
                )
                self.scale_up(node_id, _event=evt)
                events.append(evt)

            elif active_tasks <= self.idle_threshold and status not in ("spawning", "error"):
                evt = ScaleEvent(
                    node_id=node_id,
                    event_type="scale_down",
                    reason=(
                        f"active_tasks={active_tasks} at or below "
                        f"idle_threshold={self.idle_threshold}"
                    ),
                    active_tasks=active_tasks,
                )
                self.scale_down(node_id, _event=evt)
                events.append(evt)

            else:
                # Node is healthy — clear any stale recommendation
                self._remove_recommendation(node_id)

        logger.debug("check_load: %d events generated from %d nodes", len(events), len(nodes))
        return events

    def scale_up(self, node_id: str, *, _event: Optional[ScaleEvent] = None) -> None:
        """
        Record a scale-up recommendation for node_id.

        Generates (or reuses) a ScaleEvent and persists it to autoscaler.jsonl.
        The caller should act on the recommendation (e.g. spawn a sibling node).
        """
        evt = _event or ScaleEvent(
            node_id=node_id,
            event_type="scale_up",
            reason="manual scale_up requested",
        )
        self._append_log(evt)
        self._upsert_recommendation(evt)
        logger.info("SCALE_UP recommended for node '%s': %s", node_id, evt.reason)

    def scale_down(self, node_id: str, *, _event: Optional[ScaleEvent] = None) -> None:
        """
        Record a scale-down recommendation for node_id.

        Marks the node as an idle candidate in autoscaler.jsonl.
        The caller should act on the recommendation (e.g. retire the node).
        """
        evt = _event or ScaleEvent(
            node_id=node_id,
            event_type="scale_down",
            reason="manual scale_down requested",
        )
        self._append_log(evt)
        self._upsert_recommendation(evt)
        logger.info("SCALE_DOWN recommended for node '%s': %s", node_id, evt.reason)

    def get_recommendations(self) -> list[dict]:
        """
        Return all active scaling recommendations.

        Triggers check_load() on first call to populate recommendations.
        Each entry is a dict representation of the last ScaleEvent for that node.
        """
        if not self._recommendations:
            self.check_load()
        return list(self._recommendations.values())


# ═══════════════════════════════════════════════════════
# DEMO
# ═══════════════════════════════════════════════════════

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s — %(message)s")

    import tempfile

    # Create a temporary mesh directory with synthetic nodes.json
    with tempfile.TemporaryDirectory() as tmp:
        log_dir = Path(tmp)
        nodes_file = log_dir / "nodes.json"
        nodes_file.write_text(
            json.dumps({
                "architect": {"active_tasks": 8, "status": "active"},
                "researcher": {"active_tasks": 3, "status": "active"},
                "guardian": {"active_tasks": 0, "status": "idle"},
                "narrator": {"active_tasks": 0, "status": "spawning"},
            }),
            encoding="utf-8",
        )

        scaler = MeshAutoScaler(
            overload_threshold=5,
            idle_threshold=0,
            check_interval=30,
            log_dir=log_dir,
        )

        print("\n── check_load() ─────────────────────────────")
        events = scaler.check_load()
        for evt in events:
            print(f"  [{evt.event_type.upper()}] {evt.node_id}: {evt.reason}")

        print("\n── get_recommendations() ────────────────────")
        for rec in scaler.get_recommendations():
            print(f"  {rec['node_id']:15s} → {rec['event_type']}  ({rec['reason']})")

        autoscaler_log = log_dir / "autoscaler.jsonl"
        if autoscaler_log.exists():
            lines = autoscaler_log.read_text(encoding="utf-8").strip().splitlines()
            print(f"\n── autoscaler.jsonl ({len(lines)} entries) ─────────")
            for line in lines:
                entry = json.loads(line)
                print(f"  {entry['node_id']:15s} {entry['event_type']:12s} ts={entry['timestamp']:.2f}")

        # Demonstrate manual calls
        print("\n── manual scale_up / scale_down ─────────────")
        scaler.scale_up("reviewer")
        scaler.scale_down("narrator")
        for rec in scaler.get_recommendations():
            print(f"  {rec['node_id']:15s} → {rec['event_type']}")
