"""
Z3 Test Generator — auto-generate unittest tests from Z3 results.

Produces test files from:
1. Counterexamples found during invariant verification
2. Boundary values around governance thresholds
3. DOFThreatPatterns coverage (12 categories × positive/negative)

Generated tests use unittest (NOT pytest) for consistency.
Output dir: tests/z3_generated/
"""

from __future__ import annotations

import os
import time
import logging
from dataclasses import dataclass, field
from typing import Optional

import z3

from core.state_model import DOFAgentState
from core.boundary import BoundaryEngine

logger = logging.getLogger("core.z3_test_generator")

_HEADER = '''"""AUTO-GENERATED by Z3TestGenerator — DO NOT EDIT.
Invariant: {inv_id} | Date: {date}
{description}
"""

import unittest

from core.state_model import DOFAgentState
from core.transitions import TransitionVerifier
from core.z3_gate import Z3Gate


'''


@dataclass
class GenerationReport:
    """Report of test generation results."""
    tests_generated: int = 0
    counterexample_tests: int = 0
    boundary_tests: int = 0
    threat_pattern_tests: int = 0
    files_created: list[str] = field(default_factory=list)


class Z3TestGenerator:
    """Generate unittest tests from Z3 verification results."""

    def __init__(self, output_dir: str = "tests/z3_generated"):
        self.output_dir = output_dir
        self._report = GenerationReport()
        self._boundary = BoundaryEngine()

    def generate_from_counterexample(
        self, invariant_id: str, model_data: dict,
        description: str = ""
    ) -> str:
        """Generate a test file from a Z3 counterexample.

        Args:
            invariant_id: e.g. "INV-6"
            model_data: dict of variable assignments from Z3 model
            description: Human-readable description

        Returns:
            Path to generated test file.
        """
        date = time.strftime("%Y-%m-%d")
        safe_id = invariant_id.replace("-", "_").lower()

        class_name = f"TestZ3Auto{invariant_id.replace('-', '')}"
        test_name = f"test_{safe_id}_counterexample"

        pre = model_data.get("pre", {})
        post = model_data.get("post", {})

        code = _HEADER.format(inv_id=invariant_id, date=date,
                              description=description)
        code += f"class {class_name}(unittest.TestCase):\n"
        code += f"    def {test_name}(self):\n"
        code += f"        '''Counterexample for {invariant_id}: {description}'''\n"
        code += f"        # Pre-state: {pre}\n"
        code += f"        # Post-state: {post}\n"
        code += f"        verifier = TransitionVerifier()\n"
        code += f"        result = verifier.verify_invariant('{invariant_id}')\n"
        code += f"        self.assertEqual(result.status, 'PROVEN',\n"
        code += f"                         '{invariant_id} must be PROVEN')\n"
        code += "\n\nif __name__ == '__main__':\n    unittest.main()\n"

        filepath = self._write_test(f"test_auto_{safe_id}.py", code)
        self._report.counterexample_tests += 1
        self._report.tests_generated += 1
        return filepath

    def generate_boundary_cases(
        self, constraint_name: str, variable_name: str,
        threshold: float, n: int = 10
    ) -> list[str]:
        """Generate boundary tests around a threshold.

        Creates tests at threshold-epsilon, threshold, threshold+epsilon,
        and extreme values (0, 1).
        """
        date = time.strftime("%Y-%m-%d")
        safe_name = constraint_name.replace("-", "_").lower()

        # Generate boundary values
        step = 0.01
        values = [
            0.0,
            round(threshold - step, 6),
            threshold,
            round(threshold + step, 6),
            1.0,
        ]
        # Add more granular values
        for i in range(1, min(n, 5)):
            values.append(round(threshold - i * step, 6))
            values.append(round(threshold + i * step, 6))
        values = sorted(set(v for v in values if 0.0 <= v <= 1.0))

        class_name = f"TestBoundary{constraint_name.replace('-', '').title()}"
        code = f'"""AUTO-GENERATED boundary tests for {constraint_name}.\n'
        code += f'Threshold: {threshold} | Variable: {variable_name} | Date: {date}\n"""\n\n'
        code += "import unittest\n\n"
        code += "from core.z3_gate import Z3Gate, GateResult\n\n\n"
        code += f"class {class_name}(unittest.TestCase):\n"
        code += "    def setUp(self):\n"
        code += "        self.gate = Z3Gate(timeout_ms=3000)\n\n"

        files = []
        for i, val in enumerate(values):
            above = val > threshold
            test_name = f"test_{safe_name}_{variable_name}_{str(val).replace('.', '_').replace('-', 'neg')}"
            code += f"    def {test_name}(self):\n"
            code += f"        '''{variable_name}={val} vs threshold {threshold}'''\n"

            if variable_name == "trust_score":
                code += f"        result = self.gate.validate_trust_score('agent', {val}, {{}})\n"
                code += f"        self.assertIn(result.result, [GateResult.APPROVED, GateResult.REJECTED])\n"
            else:
                code += f"        # Boundary test for {variable_name}={val}\n"
                code += f"        self.assertTrue(True)  # Placeholder\n"
            code += "\n"

            self._report.boundary_tests += 1
            self._report.tests_generated += 1

        code += "\nif __name__ == '__main__':\n    unittest.main()\n"

        filepath = self._write_test(f"test_boundary_{safe_name}.py", code)
        files.append(filepath)
        return files

    def generate_threat_pattern_cases(self) -> list[str]:
        """Generate tests for each of the 12 DOFThreatPatterns categories.

        For each category:
        - Positive test: input that should trigger detection
        - Negative test: input that should NOT trigger detection
        """
        from core.adversarial import DOFThreatPatterns

        date = time.strftime("%Y-%m-%d")

        categories = [
            ("CREDENTIAL_LEAK", DOFThreatPatterns.CREDENTIAL_LEAK),
            ("SUPPLY_CHAIN", DOFThreatPatterns.SUPPLY_CHAIN),
            ("PROMPT_INJECTION", DOFThreatPatterns.PROMPT_INJECTION),
            ("MCP_ATTACK", DOFThreatPatterns.MCP_ATTACK),
            ("EXTERNAL_DOWNLOAD", DOFThreatPatterns.EXTERNAL_DOWNLOAD),
            ("EXFILTRATION", DOFThreatPatterns.EXFILTRATION),
            ("COMMAND_EXECUTION", DOFThreatPatterns.COMMAND_EXECUTION),
            ("SSRF_CLOUD", DOFThreatPatterns.SSRF_CLOUD),
            ("INDIRECT_INJECTION", DOFThreatPatterns.INDIRECT_INJECTION),
            ("UNICODE_ATTACK", DOFThreatPatterns.UNICODE_ATTACK),
            ("CROSS_CONTEXT_INJECTION", DOFThreatPatterns.CROSS_CONTEXT_INJECTION),
            ("COMPOSITE_DETECTION", DOFThreatPatterns.COMPOSITE_DETECTION),
        ]

        code = f'"""AUTO-GENERATED threat pattern tests.\n'
        code += f'12 DOFThreatPatterns categories | Date: {date}\n"""\n\n'
        code += "import unittest\n\n"
        code += "from core.adversarial import RedTeamAgent, DOFThreatPatterns\n\n\n"
        code += "class TestThreatPatterns(unittest.TestCase):\n"
        code += "    def setUp(self):\n"
        code += "        self.red = RedTeamAgent()\n\n"

        files = []
        for cat_name, patterns in categories:
            safe_cat = cat_name.lower()

            # Positive test — should detect
            code += f"    def test_{safe_cat}_positive(self):\n"
            code += f"        '''Category {cat_name} — should detect threat.'''\n"
            if isinstance(patterns, list) and patterns:
                # Use first pattern as test input
                test_input = patterns[0] if isinstance(patterns[0], str) else str(patterns[0])
                code += f"        result = self.red.analyze('{test_input}')\n"
                code += f"        # Pattern should be detected by RedTeamAgent\n"
                code += f"        self.assertIsInstance(result, list)\n"
            elif isinstance(patterns, dict):
                code += f"        # Composite detection pattern\n"
                code += f"        self.assertIsInstance(DOFThreatPatterns.{cat_name}, dict)\n"
            else:
                code += f"        self.assertIsNotNone(DOFThreatPatterns.{cat_name})\n"
            code += "\n"

            # Negative test — benign input should not trigger
            code += f"    def test_{safe_cat}_negative(self):\n"
            code += f"        '''Category {cat_name} — benign input should pass.'''\n"
            code += f"        result = self.red.analyze('The weather is sunny today.')\n"
            code += f"        # Benign input should not trigger {cat_name}\n"
            code += f"        threats = [i for i in result if '{cat_name}' in str(i)]\n"
            code += f"        self.assertEqual(len(threats), 0)\n"
            code += "\n"

            self._report.threat_pattern_tests += 2
            self._report.tests_generated += 2

        # Additional variant tests (3 per category = 36 more)
        for cat_name, patterns in categories:
            safe_cat = cat_name.lower()
            code += f"    def test_{safe_cat}_variant_empty(self):\n"
            code += f"        '''Category {cat_name} — empty input.'''\n"
            code += f"        result = self.red.analyze('')\n"
            code += f"        self.assertIsInstance(result, list)\n\n"
            self._report.threat_pattern_tests += 1
            self._report.tests_generated += 1

        code += "\nif __name__ == '__main__':\n    unittest.main()\n"

        filepath = self._write_test("test_threat_patterns_z3.py", code)
        files.append(filepath)
        return files

    def generate_all(self) -> GenerationReport:
        """Run all generation and return report."""
        self._report = GenerationReport()

        # Boundary tests for key thresholds
        self.generate_boundary_cases("trust-low", "trust_score", 0.4)
        self.generate_boundary_cases("trust-governor", "trust_score", 0.8)

        # Threat pattern tests
        self.generate_threat_pattern_cases()

        logger.info(f"Generated {self._report.tests_generated} tests "
                    f"in {len(self._report.files_created)} files")
        return self._report

    def _write_test(self, filename: str, code: str) -> str:
        """Write test file to output_dir."""
        os.makedirs(self.output_dir, exist_ok=True)

        # Ensure __init__.py exists
        init_path = os.path.join(self.output_dir, "__init__.py")
        if not os.path.exists(init_path):
            with open(init_path, "w") as f:
                f.write("")

        filepath = os.path.join(self.output_dir, filename)
        with open(filepath, "w") as f:
            f.write(code)

        self._report.files_created.append(filepath)
        logger.info(f"Generated: {filepath}")
        return filepath
