#!/usr/bin/env bash
# start_ollama_cluster.sh — Start 3 Ollama instances on ports 11434, 11435, 11436
# Port 11434: primary (managed by LaunchAgent — just verify alive)
# Port 11435: secondary (started here)
# Port 11436: tertiary (started here)

set -euo pipefail

PORTS=(11434 11435 11436)
ENV_FILE="$(dirname "$(dirname "$(realpath "$0")")")/logs/ollama_cluster.env"
STARTUP_WAIT=3

log() { echo "[ollama-cluster] $*"; }

is_alive() {
    local port=$1
    curl -sf --max-time 2 "http://localhost:${port}/api/tags" > /dev/null 2>&1
}

# ── 1. Check primary (11434) ───────────────────────────────────────────────
log "Checking primary instance on port 11434..."
if is_alive 11434; then
    log "  ✓ Port 11434 is alive (LaunchAgent managed)"
else
    log "  ✗ Port 11434 is NOT responding — trying to start it..."
    OLLAMA_HOST=0.0.0.0:11434 ollama serve &
    sleep $STARTUP_WAIT
    if is_alive 11434; then
        log "  ✓ Port 11434 started successfully"
    else
        log "  ✗ Port 11434 still not responding — continuing anyway"
    fi
fi

# ── 2. Start secondary (11435) ────────────────────────────────────────────
log "Starting secondary instance on port 11435..."
if is_alive 11435; then
    log "  ✓ Port 11435 already alive — skipping start"
else
    OLLAMA_HOST=0.0.0.0:11435 ollama serve > /tmp/ollama_11435.log 2>&1 &
    log "  Waiting ${STARTUP_WAIT}s for port 11435 to initialize..."
    sleep $STARTUP_WAIT
fi

# ── 3. Start tertiary (11436) ─────────────────────────────────────────────
log "Starting tertiary instance on port 11436..."
if is_alive 11436; then
    log "  ✓ Port 11436 already alive — skipping start"
else
    OLLAMA_HOST=0.0.0.0:11436 ollama serve > /tmp/ollama_11436.log 2>&1 &
    log "  Waiting ${STARTUP_WAIT}s for port 11436 to initialize..."
    sleep $STARTUP_WAIT
fi

# ── 4. Verify all three ───────────────────────────────────────────────────
log ""
log "=== Cluster Status ==="
ALIVE_PORTS=()
ALL_OK=true

for port in "${PORTS[@]}"; do
    if is_alive "$port"; then
        log "  [UP]   http://localhost:${port}"
        ALIVE_PORTS+=("$port")
    else
        log "  [DOWN] http://localhost:${port}"
        ALL_OK=false
    fi
done

# ── 5. Write env file ─────────────────────────────────────────────────────
mkdir -p "$(dirname "$ENV_FILE")"
CLUSTER_PORTS_VALUE=$(IFS=,; echo "${ALIVE_PORTS[*]}")
{
    echo "# Auto-generated by start_ollama_cluster.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "OLLAMA_CLUSTER_PORTS=${CLUSTER_PORTS_VALUE}"
    echo "OLLAMA_CLUSTER_ALIVE=${#ALIVE_PORTS[@]}"
    echo "OLLAMA_CLUSTER_TOTAL=${#PORTS[@]}"
} > "$ENV_FILE"

log ""
log "Env written to: $ENV_FILE"
log "OLLAMA_CLUSTER_PORTS=${CLUSTER_PORTS_VALUE}"
log ""

if $ALL_OK; then
    log "All 3 Ollama instances are UP — cluster ready."
    exit 0
else
    log "WARNING: Some instances are DOWN. Active ports: ${CLUSTER_PORTS_VALUE:-none}"
    exit 1
fi
